### ISSUE TITLE
Team Project Evaluation and Grades

### ISSUE THREAD

**Issue by ThibaultWalterspieler** [AlexisCro/ISITECH-L2-infra-dev-grp-1#15]
| Student Name  | Grade | Comment                |
|---------------|-------|------------------------|
| Clément BERARD     | 17.2   | Pay attention to the regularity of upper/lower case in your commits. When you open a PR, remember to always describe it (changes, implications, breaking changes...) |
| Alexis CROZIER     | 17.2  | Pay attention to the regularity of upper/lower case in your commits. Very good review of the PRs, well done. When you open a PR, remember to always describe it (changes, implications, breaking changes...). Very good respect of your PO’s role |
| Matéo DEPORT     | 17   | Pay attention to the semantics of your commit messages. e.g. ‘sup file navbar.tsx’ means nothing. Use correct English. If you're having trouble with this, don't hesitate to use deepl or similar. When you open a PR, remember to always describe it (changes, implications, breaking changes...)   |
| Ruben CROCHET | 0  |  No contributions to this project |
---

### Group Comment:
- Be careful about PRs naming
- No definition of rules for naming commits and PRs in the CONTRIBUTING.md
- No explanations of the purpose of the branches of your branching strategy
- You still had plenty of time to make the switch from CRA/Jest to Vite.js/Vitest. However, your justification of the choice to not make the switch is valid. 
- Your unit test works but is of no real use. You’re more testing the ability of JS to detect types than a real functionality of your app. You could have unit tested the searchMovie() function instead https://github.com/AlexisCro/ISITECH-L2-infra-dev-grp-1/blob/ea824083fa3d63237c9d7b5770c7941a4d84af8a/src/App.tsx#L25
- Testing whether localStorage interacts well with your app is a good use case for an integration test. However, your implementation tests the native operations on localStorage but not its interaction with your code/application. 
- No github actions are configured for the main branch. These actions runs only on the develop branch
- The App.e2e.test.tsx file defined as your E2E testing file is not an E2E test. To be an E2E test, it has to launch the whole app not just render the <App /> component. You have to use dedicated libraries such as playwright, puppeteer, cypress etc.

👏 Well done for the rest, your app is functional, with a well-described brief and effective project management. However, be careful to follow the instructions. Congratulations! 👏

**Comment by AlexisCro** [comment]
@ThibaultWalterspieler for your return, you're the first instructor guving us a return and correction. 
This is really appreciate.
